version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command: "air -c ./build/.air.toml"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/go/base
    tty: true
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data
      - ./build/postgres/initdb.d:/docker-entrypoint-initdb.d
